const express = require('express');
const router = express.Router();
const { AnalysisResult } = require('../../models');
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const REPORTS_DIR = path.join(__dirname, '../../reports');

// Ensure reports directory exists
if (!fs.existsSync(REPORTS_DIR)) {
  fs.mkdirSync(REPORTS_DIR, { recursive: true });
}

/**
 * POST /api/reports/generate
 * Generate a report for a region
 */
router.post('/generate', async (req, res) => {
  try {
    const { regionName, format = 'pdf', dateRange = '7days', includeHistory = true, reportType = 'detailed' } = req.body;

    if (!regionName) {
      return res.status(400).json({
        success: false,
        message: 'Region name is required',
      });
    }

    // Fetch analysis history for the region
    let query = { regionName };
    const now = new Date();

    // Apply date range filter
    switch (dateRange) {
      case '7days':
        query.timestamp = { $gte: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000) };
        break;
      case '30days':
        query.timestamp = { $gte: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000) };
        break;
      case '90days':
        query.timestamp = { $gte: new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000) };
        break;
      // 'all' - no date filter
    }

    const analyses = await AnalysisResult.find(query).sort({ timestamp: -1 });

    // Create report with fallback data if no analyses exist
    const reportData = {
      region: regionName,
      dateRange,
      reportType,
      generatedAt: new Date(),
      latestAnalysis: analyses.length > 0 ? analyses[0] : {
        regionName,
        riskClassification: { riskLevel: 'MEDIUM', vegetationLossPercentage: 0, confidenceScore: 0.75 }
      },
      historicalData: includeHistory ? analyses : [],
      summary: analyses.length > 0 ? {
        totalAnalyses: analyses.length,
        dateRange: `${analyses[analyses.length - 1].timestamp.toLocaleDateString()} - ${analyses[0].timestamp.toLocaleDateString()}`,
        currentRiskLevel: analyses[0].riskClassification?.riskLevel || 'MEDIUM',
        averageVegetationLoss: (analyses.reduce((sum, a) => sum + (a.riskClassification?.vegetationLossPercentage || 0), 0) / analyses.length).toFixed(2),
        confidenceScore: (analyses[0].riskClassification?.confidenceScore * 100 || 75).toFixed(1),
      } : {
        totalAnalyses: 0,
        dateRange: 'No data',
        currentRiskLevel: 'MEDIUM',
        averageVegetationLoss: '0.00',
        confidenceScore: '75.0',
      },
    };

    // Generate PDF if requested
    if (format === 'pdf') {
      const filename = `report-${regionName.replace(/\s+/g, '_')}-${Date.now()}.pdf`;
      const filepath = path.join(REPORTS_DIR, filename);

      return new Promise((resolve) => {
        const doc = new PDFDocument();
        const stream = fs.createWriteStream(filepath);

        doc.pipe(stream);

        // Title
        doc.fontSize(24).font('Helvetica-Bold').text('📊 Satellite Change Detection Report', { align: 'center' }).moveDown();
        doc.fontSize(10).text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' }).moveDown(1);

        // Region Information
        doc.fontSize(14).font('Helvetica-Bold').text('Region Information', { underline: true }).moveDown(0.5);
        doc.fontSize(11).font('Helvetica')
          .text(`Region: ${regionName}`)
          .text(`Report Type: ${reportType}`)
          .text(`Date Range: ${reportData.summary.dateRange}`)
          .moveDown(1);

        // Summary Section
        doc.fontSize(14).font('Helvetica-Bold').text('Summary', { underline: true }).moveDown(0.5);
        doc.fontSize(11).font('Helvetica')
          .text(`Current Risk Level: ${reportData.summary.currentRiskLevel}`)
          .text(`Total Analyses: ${reportData.summary.totalAnalyses}`)
          .text(`Average Vegetation Loss: ${reportData.summary.averageVegetationLoss}%`)
          .text(`Confidence Score: ${reportData.summary.confidenceScore}%`)
          .moveDown(1);

        // Latest Analysis
        if (reportData.latestAnalysis) {
          doc.fontSize(14).font('Helvetica-Bold').text('Latest Analysis', { underline: true }).moveDown(0.5);
          const latest = reportData.latestAnalysis;
          doc.fontSize(11).font('Helvetica')
            .text(`NDVI Mean: ${latest.ndvi?.mean || 'N/A'}`)
            .text(`Risk Level: ${latest.riskClassification?.riskLevel || 'N/A'}`)
            .text(`Vegetation Loss: ${latest.riskClassification?.vegetationLossPercentage || 0}%`)
            .moveDown(1);
        }

        // Footer
        doc.fontSize(9).text('This report was automatically generated by the Satellite Change Detection System', { align: 'center' });

        doc.end();

        stream.on('finish', () => {
          res.json({
            success: true,
            message: 'Report generated successfully',
            filename,
            format: 'pdf',
            report: reportData,
          });
          resolve();
        });

        stream.on('error', (err) => {
          res.status(500).json({
            success: false,
            message: 'Failed to generate PDF',
            error: err.message,
          });
          resolve();
        });
      });
    }

    // Return JSON for other formats
    res.json({
      success: true,
      message: 'Report generated successfully',
      report: reportData,
      format: format,
    });
  } catch (error) {
    console.error('Error generating report:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to generate report',
      error: error.message,
    });
  }
});

/**
 * GET /api/reports/list
 * List all available reports
 */
router.get('/list', async (req, res) => {
  try {
    if (!fs.existsSync(REPORTS_DIR)) {
      return res.json({
        success: true,
        reports: [],
      });
    }

    const files = fs.readdirSync(REPORTS_DIR);
    const reports = files.map((filename) => {
      const filePath = path.join(REPORTS_DIR, filename);
      const stats = fs.statSync(filePath);
      const ext = path.extname(filename);

      return {
        filename,
        name: filename.replace(/^report-/, '').replace(/\.\w+$/, ''),
        format: ext.substring(1).toUpperCase(),
        size: stats.size,
        createdAt: stats.birthtime,
      };
    });

    res.json({
      success: true,
      count: reports.length,
      reports: reports.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)),
    });
  } catch (error) {
    console.error('Error listing reports:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to list reports',
      error: error.message,
    });
  }
});

/**
 * GET /api/reports/download/:filename
 * Download a report
 */
router.get('/download/:filename', async (req, res) => {
  try {
    const filename = req.params.filename;
    const filePath = path.join(REPORTS_DIR, filename);

    // Security check: prevent directory traversal
    if (!path.resolve(filePath).startsWith(path.resolve(REPORTS_DIR))) {
      return res.status(403).json({
        success: false,
        message: 'Access denied',
      });
    }

    if (!fs.existsSync(filePath)) {
      return res.status(404).json({
        success: false,
        message: 'Report not found',
      });
    }

    // Determine content type
    const ext = path.extname(filename).toLowerCase();
    let contentType = 'application/octet-stream';
    if (ext === '.pdf') contentType = 'application/pdf';
    else if (ext === '.csv') contentType = 'text/csv';
    else if (ext === '.json') contentType = 'application/json';

    res.setHeader('Content-Type', contentType);
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

    const fileStream = fs.createReadStream(filePath);
    fileStream.pipe(res);
  } catch (error) {
    console.error('Error downloading report:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to download report',
      error: error.message,
    });
  }
});

/**
 * DELETE /api/reports/:filename
 * Delete a report
 */
router.delete('/:filename', async (req, res) => {
  try {
    const filename = req.params.filename;
    const filePath = path.join(REPORTS_DIR, filename);

    // Security check: prevent directory traversal
    if (!path.resolve(filePath).startsWith(path.resolve(REPORTS_DIR))) {
      return res.status(403).json({
        success: false,
        message: 'Access denied',
      });
    }

    if (!fs.existsSync(filePath)) {
      return res.status(404).json({
        success: false,
        message: 'Report not found',
      });
    }

    fs.unlinkSync(filePath);

    res.json({
      success: true,
      message: 'Report deleted successfully',
    });
  } catch (error) {
    console.error('Error deleting report:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to delete report',
      error: error.message,
    });
  }
});

module.exports = router;
